<?php
global $lang;
?>
<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $lang['ECMAppName']; ?></title>
</head>
<body>
    <h1><?php echo $lang['ECMErrorMessage']; ?></h1>
    <p><?php echo $this->errorMessage; ?></p>
</body>
</html>
