<?php
/**
 * Entity Class for Table [tbl_account]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */

/**
 * Entity Class เก็บบัญชีรายชื่อ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 * 
 */
class AccountEntity extends ADODB_Active_Record {
	/**
	 * _table  เก็บชื่อ Table Mapping
	 *
	 * @var string
	 */
	public $_table = 'tbl_account';
	/**
	 * รหัสผู้ใช้งาน
	 *
	 * @var integer
	 */
	public $f_acc_id;
	/**
	 * Login name
	 *
	 * @var string
	 */
	public $f_login_name;
	/**
	 * Password (MD5 Hash)
	 *
	 * @var string
	 */
	public $f_login_password;
	/**
	 * ชื่อ
	 *
	 * @var string
	 */
	public $f_name;
	public $f_mid_name;
	public $f_last_name;
	public $f_rank_id;
	public $f_tries;
	public $f_last_change_pwd;
	public $f_status;
	public $f_account_type;
	public $f_email;
	public $f_tel;
	public $f_fax;
	public $f_mobile;
	public $f_is_expired;
	public $f_expired;
	public $f_limit_access;
	public $f_access_from;
	public $f_access_to;
	public $f_ldap_bind;
	public $f_ldap_cn;
	public $f_dms_home;
	public $f_strict_to_home;
	public $f_force_change_pwd;
	public $f_force_change_pwd_timestamp;
	public $f_unable_to_change_pwd;
	public $f_password_hint_question;
	public $f_password_hint_answer;
}