<?php
/**
 * Entity Class for Table [tbl_bookmark]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */

/**
 * Entity Class เก็บ Bookmark
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class BookmarkEntity extends ADODB_Active_Record {
	public $_table = 'tbl_bookmark';
	public $f_bmk_id;
	public $f_owner_uid;
	public $f_owner_role_id;
	public $f_owner_org_id;
	public $f_trans_main_id;
}