<?php
/**
 * Entity Class for Table [tbl_delegate_role]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Role ที่สามารถ Delegate กันได้
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DelegateRoleEntity extends ADODB_Active_Record {
	public $_table = 'tbl_delegate_role';
	public $f_role_id;
	public $f_delegate_role_id;
	public $f_delegate_level;
}