<?php
/**
 * Entity Class for Table [tbl_df_route]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บเส้นทางของ DocFlow
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DfRouteEntity extends ADODB_Active_Record {
	public $_table = 'tbl_df_route';
	public $f_df_route_id;
	public $f_df_route_name;
	public $f_owner_type;
	public $f_owner_uid;
	public $f_owner_role_id;
	public $f_owner_org_id;
	public $f_public_access;
	public $f_route_status;
}