<?php
/**
 * Entity Class for Table [tbl_dms_my_object]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บโครงสร้างเอกสารใน My Document
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DmsMyObjectEntity extends ADODB_Active_Record {
	public $_table = 'tbl_dms_my_object';
	public $f_myobj_id;
	public $f_myobj_pid;
	public $f_myobj_type;
	public $f_owner_id;
	public $f_name;
	public $f_description;
	public $f_keyword;
	public $f_location;
	public $f_doc_id;
	public $f_created_stamp;
	public $f_mark_delete;
	public $f_delete;
	public $f_last_update_stamp;
	public $f_published;
	public $f_status;
	public $f_is_expired;
	public $f_expire;
}