<?php
/**
 * Entity Class for Table [tbl_doc_main]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บข้อมูลของเอกสารหลัก
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DocMainEntity extends ADODB_Active_Record {
	public $_table = 'tbl_doc_main';
	public $f_doc_id;
	public $f_form_id;
	public $f_form_version;
	public $f_title;
	public $f_doc_revision=1;
	public $f_active;
	public $f_description;
	public $f_doc_no;
	public $f_doc_date;
	public $f_doc_stamp;
	public $f_flowed;
	public $f_dms_indexed;
	public $f_flow_type;
	public $f_create_stamp;
	public $f_create_uid;
	public $f_create_role_id;
	public $f_create_org_id;
	public $f_last_update_stamp;
	public $f_last_update_user;
	public $f_last_update_role_id;
	public $f_last_update_org_id;
	public $f_mark_delete;
	public $f_mark_delete_uid;
	public $f_mark_delete_role_id;
	public $f_mark_delete_org_id;
	public $f_delete;
	public $f_delete_uid;
	public $f_delete_role_id;
	public $f_delete_org_id;
	public $f_status;
	public $f_lifecycle;
	public $f_security_modifier;
	public $f_urgent_modifier;
	public $f_signed;
	public $f_sign_uid;
	public $f_sign_role_id;
	public $f_sign_org_id;
	public $f_owner_type;
	public $f_owner_uid;
	public $f_owner_role_id;
	public $f_owner_org_id;
	public $f_expired_date;
	public $f_location_id;
	public $f_refer;
	public $f_attach;
	public $f_detail;
	public $f_remark;
	public $f_gen_int_bookno;
	public $f_gen_ext_bookno;
	public $f_gen_ext_type;
	public $f_ref_gen_from_doc_id;
	public $f_request_order;
	public $f_request_command;
	public $f_request_announce;
	public $f_doc_flag;
	public $f_version = '1.0.0';
	public $f_version_active;
	public $f_checkout_flag = 0;
	public $f_checkout_user = 0;
	public $f_is_iso = 0;
	public $f_iso_type = 0;
    public $f_effective_date = 0;
	public $f_gen_doc_org_id = 0;
	public $f_doc_realdate;
}