<?php
/**
 * Entity Class for Table [tbl_doc_type]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บประเภทของเอกสาร
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DocTypeEntity extends ADODB_Active_Record {
	public $_table = 'tbl_doc_type';
	public $f_doctype_id;
	public $f_global;
	public $f_org_id;
	public $f_name;
	public $f_status;
}