<?php
/**
 * Entity Class for Table [tbl_iso_approval_detail]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บข้อมูล ISO Approval Detail
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class IsoApprovalEntity extends ADODB_Active_Record {
    public $_table = 'tbl_iso_approval_detail';
    public $f_issue_id;
    public $f_approval_member_role_id;
    public $f_approve;
    public $f_approve_timestamp;
    public $f_approve_uid;
    public $f_comment;    
}