<?php
/**
 * Entity Class for Table [tbl_kb_object]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ KBase Object
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class KbObjectEntity extends ADODB_Active_Record {
	public $_table = 'tbl_kb_object';
	public $f_kb_id;
	public $f_kb_pid;
	public $f_kb_type;
	public $f_name;
	public $f_description;
	public $f_keyword;
	public $f_doc_id;
	public $f_created_uid;
	public $f_created_role_id;
	public $f_created_org_id;
	public $f_created_stamp;
	public $f_mark_delete;
	public $f_mark_delete_uid;
	public $f_mark_delete_role_id;
	public $f_mark_delete_org_id;
	public $f_delete;
	public $f_delete_uid;
	public $f_delete_role_id;
	public $f_delete_org_id;
	public $f_last_update_stamp;
	public $f_last_update_uid;
	public $f_last_update_role_id;
	public $f_last_update_org_id;
	public $f_locked;
	public $f_password;
	public $f_checkout;
	public $f_checkout_uid;
	public $f_checkout_role_id;
	public $f_checkout_org_id;
	public $f_owner_type;
	public $f_owner_uid;
	public $f_owner_role_id;
	public $f_owner_org_id;
	public $f_status;
}