<?php
/**
 * Entity Class for Table [tbl_lookup]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */

/**
 * Entity Class เก็บข้อมูล Lookup
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class LookupEntity extends ADODB_Active_Record {
	public $_table = 'tbl_lookup';
	public $f_lookup_id;
	public $f_lookup_name;
	public $f_lookup_desc;
	public $f_lookup_type;
	public $f_lookup_def;
	public $f_lookup_source;
}