<?php
/**
 * Entity Class for Table [tbl_media_structure]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ โครงสร้าง Media
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class MediaStructureEntity extends ADODB_Active_Record {
	public $_table = 'tbl_media_structure';
	public $f_media_id;
	public $f_obj_type;
	public $f_obj_id;
}