<?php
/**
 * Entity Class for Table [tbl_page_contents]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Fulltext Content ของเอกสาร
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class PageContentsEntity extends ADODB_Active_Record {
	public $_table = 'tbl_page_contents';
	public $f_doc_id;
	public $f_page_id;
	public $f_major_version;
	public $f_minor_version;
	public $f_branch_version;
	public $f_contents;
}