<?php
/**
 * Entity Class for Table [tbl_portlet]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ รายการ Portlet
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class PortletEntity extends ADODB_Active_Record {
	public $_table = 'tbl_portlet';
	public $f_portlet_id;
	public $f_portlet_name;
	public $f_portlet_class;
	public $f_portlet_method;
	public $f_portlet_status;
	public $f_portlet_access_level;
}