<?php
/**
 * Entity Class for Table [tbl_position_master]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Position Master
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class PositionMasterEntity extends ADODB_Active_Record {
	public $_table = 'tbl_position_master';
	public $f_pos_id;
	public $f_pos_name;
	public $f_pos_desc;
	public $f_pos_level;
	public $f_pos_status;
}