<?php
/**
 * Entity Class for Table [tbl_reg_book]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บรายการทะเบียนหนังสือ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class RegBookEntity extends ADODB_Active_Record {
	public $_table = 'tbl_reg_book';
	public $f_reg_book_id;
	public $f_reg_book_type;
	public $f_reg_book_name;
	public $f_owner_org_id;
	public $f_status;
}