<?php
/**
 * Entity Class for Table [tbl_request_action]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บประเภทการร้องขอ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class RequestActionEntity extends ADODB_Active_Record {
	public $_table = 'tbl_request_action';
	public $f_request_action_id;
	public $f_action_name;
	public $f_action_def;
	public $f_action_perform;
	public $f_action_type;
	public $f_status;
}