<?php
/**
 * Entity Class for Table [tbl_role]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บตำแหน่ง
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class RoleEntity extends ADODB_Active_Record {
	public $_table = 'tbl_role';
	public $f_role_id;
	public $f_role_name;
	public $f_role_desc;
	public $f_role_status;
	public $f_pos_id;
	public $f_org_id;
	public $f_gp_id;
	public $f_role_is_expire;
	public $f_rol_expire;
	public $f_role_is_effective;
	public $f_role_effective;
	public $f_is_governer;
    public $f_dar_approval = 0;
    public $f_is_qmr = 0;
    public $f_iso_approval = 0;
    public $f_dcc = 0;
    public $f_unlimit_lookup = 0;
	public $f_is_commander = 0;
}