<?php
/**
 * Entity Class for Table [tbl_role_replacement]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บตำแหน่งทดแทน
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class RoleReplacementEntity extends ADODB_Active_Record {
	public $_table = 'tbl_role_replacement';
	public $f_role_id;
	public $f_acc_id;
	public $f_limit_policy;
	public $f_gp_id;
	public $f_is_effective;
	public $f_effective;
	public $f_is_expired;
	public $f_expire;
}