<?php
/**
 * Entity Class for Table [tbl_seealso]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ See Also
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class SeealsoEntity extends ADODB_Active_Record {
	public $_table = 'tbl_seealso';
	public $f_doc_id;
	public $f_ref_doc_id;
	public $f_page_id;
}