<?php
/**
 * Entity Class for Table [tbl_storage]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Storage
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class StorageEntity extends ADODB_Active_Record {
	public $_table = 'tbl_storage';
	public $f_st_id;
	public $f_st_name;
	public $f_st_type;
	public $f_st_server;
	public $f_st_port;
	public $f_st_path;
	public $f_st_uid;
	public $f_st_pwd;
	public $f_st_limit;
	public $f_st_size;
	public $f_status;
	public $f_default;
}