<?php
/**
 * Entity Class for Table [tbl_workflow_instance]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Workflow Instance
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class WorkflowInstanceEntity extends ADODB_Active_Record {
	public $_table = 'tbl_workflow_instance';
	public $f_wf_instance_id;
	public $f_wf_id;
	public $f_doc_id;
	public $f_start_stamp;
	public $f_stop_stamp;
	public $f_target_stamp;
	public $f_issuer_type;
	public $f_issuer_uid;
	public $f_issuer_role_id;
	public $f_issuer_org_id;
	public $f_external_issuer_params;
	public $f_instance_status;
	public $f_notify_count;
	public $f_last_notifier_stamp;
	public $f_pause;
	public $f_pause_uid;
	public $f_pause_role_id;
	public $f_pause_org_id;
	public $f_aborted;
	public $f_abort_uid;
	public $f_abort_role_id;
	public $f_abort_org_id;
}