<?php
/**
 * Entity Class for Table [tbl_workflow_node]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Workflow Node
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class WorkflowNodeEntity extends ADODB_Active_Record {
	public $_table = 'tbl_workflow_node';
	public $f_wf_id;
	public $f_wf_revision;
	public $f_wf_node_id;
	public $f_wf_node_name;
	public $f_wf_node_type;
	public $f_distribute_mode;
	public $f_supervisor_type;
	public $f_supervisor_uid;
	public $f_supervisor_role_id;
	public $f_supervisor_org_id;
	public $f_is_work_limit;
	public $f_work_limit;
	public $f_request_action;
	public $f_extend_params;
	public $f_use_extension;
	public $f_extension;
}