<?php
/**
 * Entity Class for Table [tbl_command]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บคำสั่งการ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class CommandEntity extends ADODB_Active_Record {
	public $_table = 'tbl_command';
	public $f_cmd_id;
	public $f_type;
	public $f_trans_main_id;
	public $f_trans_main_seq;
	public $f_sub_trans_id;
	public $f_command_text;
	public $f_acc_id;
	public $f_cmd_acc_id;
	public $f_cmd_role_id;
	public $f_cmd_org_id;
	public $f_timestamp;
}