<?php
/**
 * Entity Class for Table [tbl_concurrent]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Concurrent
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class ConcurrentEntity extends ADODB_Active_Record {
	public $_table = 'tbl_concurrent';
	public $f_acc_id;
	public $f_ip_address;
	public $f_first_access;
	public $f_last_access;
	public $f_session_id;
	public $f_degrade;
}