<?php
/**
 * Entity Class for Table [tbl_df_route_table]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Route ของ DocFlow Route
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DfRouteTableEntity extends ADODB_Active_Record {
	public $_table = 'tbl_df_route_table';
	public $f_df_route_id;
	public $f_sequence;
	public $f_org_id;
	public $f_request_action;
}