<?php
/**
 * Entity Class for Table [tbl_df_stats]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class ��ʶԵԢͧ Docflow
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DfStatsEntity extends ADODB_Active_Record {
	public $_table = 'tbl_df_stats';
	public $f_trans_main_id;
	public $f_trans_main_seq;
	public $f_part_type;
	public $f_part_id;
	public $f_part_role_id;
	public $f_part_org_id;
	public $f_start_stamp;
	public $f_stop_stamp;
	public $f_total_time;
}