<?php
/**
 * Entity Class for Table [tbl_doc_hist_value]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Form History Value
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DocHistValueEntity extends ADODB_Active_Record {
	public $_table = 'tbl_doc_hist_value';
	public $f_doc_id;
	public $f_revision;
	public $f_struct_id;
	public $f_value;
}