<?php
/**
 * Entity Class for Table [tbl_doc_page_temp]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บเอกสารแนบ Temp
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DocPageTempEntity extends ADODB_Active_Record {
	public $_table = 'tbl_doc_page_temp';
	public $f_doc_id;
	public $f_page_id;
	public $f_mime_type;
	public $f_orig_file_name;
	public $f_sys_file_name;
	public $f_extension;
	public $f_file_size;
}