<?php
/**
 * Entity Class for Table [tbl_doc_page]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บเอกสารแนบของเอกสาร
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class DocPageEntity extends ADODB_Active_Record {
	public $_table = 'tbl_doc_page';
	public $f_doc_id;
	public $f_page_id;
	public $f_page_no;
	public $f_major_version;
	public $f_minor_version;
	public $f_branch_version;
	public $f_st_id;
	public $f_mime_type;
	public $f_orig_file_name;
	public $f_sys_file_name;
	public $f_extension;
	public $f_file_size;
	public $f_page_checksum;
	public $f_moved_to_storage;
	public $f_fulltext_indexed;
	public $f_create_stamp;
	public $f_create_uid;
	public $f_create_role_id;
	public $f_create_org_id;
	public $f_modified_stamp;
	public $f_modified_uid;
	public $f_modified_role_id;
	public $f_modified_org_id;
	public $f_deleted;
	public $f_delete_uid;
	public $f_delete_role_id;
	public $f_delete_org_id;
	public $f_active;
}