<?php
/**
 * Entity Class for Table [tbl_form_structure]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity class เก็บโครงสร้างของ Form
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class FormStructureEntity extends ADODB_Active_Record {
	public $_table = 'tbl_form_structure';
	public $f_form_id;
	public $f_form_version;
	public $f_struct_id;
	public $f_struct_name;
	public $f_struct_type;
	public $f_struct_group;
	public $f_data_type;
	public $f_use_lookup;
	public $f_lookup_id;
	public $f_struct_param;
	public $f_initial_value;
	public $f_is_title;
	public $f_is_desc;
	public $f_is_keyword;
	public $f_allow_search;
	public $f_is_doc_no;
	public $f_is_doc_date;
	public $f_is_required;
	public $f_is_colored;
	public $f_color;
	public $f_is_validate;
	public $f_validate_fn;
	public $f_is_sender_text;
	public $f_is_receiver_text;
	public $f_bookmark;
	public $f_is_hide;
	public $f_is_readonly;
}