<?php
/**
 * Entity Class for Table [tbl_form]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บข้อมูลของ Form
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class FormEntity extends ADODB_Active_Record {
	public $_table = 'tbl_form';
	public $f_form_id;
	public $f_form_name;
	public $f_form_desc;
	public $f_version;
	public $f_status;
	public $f_allow_wf;
	public $f_allow_dms;
	public $f_allow_df;
	public $f_allow_kb;
	public $f_allow_comment;
	public $f_allow_attach;
	public $f_default_form_df;
	public $f_default_form_dms;
	public $f_default_form_kb;
	public $f_use_orm;
	public $f_orm_def;
    public $f_form_report_id;
}