<?php
/**
 * Entity Class for Table [tbl_iso_approval]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity class เก็บข้อมูล ISO Approval
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class IsoApprovalEntity extends ADODB_Active_Record {
    public $_table = 'tbl_iso_approval';
    public $f_issue_id;
    public $f_issue_uid;
    public $f_issue_role_id;
    public $f_issue_org_id;
    public $f_doc_id;
    public $f_dar_approve;
    public $f_dar_approve_uid;
    public $f_dar_approve_role_id;
    public $f_dar_approve_org_id;
    public $f_qmr_approve;
    public $f_qmr_approve_uid;
    public $f_qmr_approve_role_id;
    public $f_qmr_approve_org_id;
    public $f_final_approve;
    public $f_publish;
    public $f_commit;
    public $f_issue_timestamp;
    public $f_dar_approve_timestamp;
    public $f_qmr_approve_timestamp;
    public $f_final_approve_timestamp;
    public $f_objective;
    public $f_detail;
    public $f_req_type = 0;
    public $f_effective_date=0;
}