<?php
/**
 * Entity Class for Table [tbl_lifecycle]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Life Cycle ของเอกสาร
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class LifecycleEntity extends ADODB_Active_Record {
	public $_table = 'tbl_lifecycle';
	public $f_lifecycle_id;
	public $f_lifecycle_type;
	public $f_lifecycle;
	public $f_lifecycle_desc;
	public $f_status;
}