<?php
/**
 * Entity Class for Table [tbl_mapping]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Mapping ต่างๆ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 * 
 *
 */
class MappingEntity extends ADODB_Active_Record {
	public $_table = 'tbl_mapping';
	public $f_map_id;
	public $f_map_class;
	public $f_master_id;
	public $f_slave_id;
}