<?php
/**
 * Entity Class for Table [tbl_notifier]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ การแจ้งเตือน
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class NotifierEntity extends ADODB_Active_Record {
	public $_table = 'tbl_notifier';
	public $f_notifier_task_type;
	public $f_notify_task_id;
	public $f_notify_task_sub_id;
	public $f_event;
	public $f_receiver_type;
	public $f_receiver_uid;
	public $f_receiver_role_id;
	public $f_receiver_org_id;
	public $f_receiver_param;
	public $f_notify_type;
	public $f_notify_message;
}