<?php
/**
 * Entity Class for Table [tbl_passport]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Passport ของบัญชีรายชื่อ/role
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class PassportEntity extends ADODB_Active_Record {
	public $_table = 'tbl_passport';
	public $f_role_id;
	public $f_acc_id;
	public $f_default_role;
}