<?php
/**
 * Entity Class for Table [tbl_preference]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Preference
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class PreferenceEntity extends ADODB_Active_Record {
	public $_table = 'tbl_preference';
	public $f_acc_id;
	public $f_pref_name;
	public $f_pref_value;
	public $f_pref_status;
}