<?php
/**
 * Entity Class for Table [tbl_rank]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บระดับขั้น
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class RankEntity extends ADODB_Active_Record {
	public $_table = 'tbl_rank';
	public $f_rank_id;
	public $f_rank_name;
	public $f_rank_desc;
	public $f_rank_level;
	public $f_rank_status;
}