<?php
/**
 * Entity Class for Table [tbl_receive_type]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บประเภทการลงรับ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class ReceiveTypeEntity extends ADODB_Active_Record {
	public $_table = 'tbl_receive_type';
	public $f_recv_id;
	public $f_recv_name;
	public $f_recv_desc;
	public $f_status;
}