<?php
/**
 * Entity Class for Table [tbl_report_category]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บรายการประเภทรายงาน
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class ReportCategoryEntity extends ADODB_Active_Record {
	public $_table = 'tbl_report_category';
	public $f_rpt_cat_id;
	public $f_rpt_cat_name;
}