<?php
/**
 * Entity Class for Table [tbl_script_db]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Script ต่างๆ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class ScriptDbEntity extends ADODB_Active_Record {
	public $_table = 'tbl_script_db';
	public $f_obj_type;
	public $f_obj_id;
	public $f_event_name;
	public $f_revision;
	public $f_script;
	public $f_checkout;
	public $f_acc_id;
}