<?php
/**
 * Entity Class for Table [tbl_security_property]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Security Property
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class SecurityPropertyEntity extends ADODB_Active_Record {
	public $_table = 'tbl_security_property';
	public $f_obj_type;
	public $f_obj_id;
	public $f_security_prop_type;
	public $f_security_context_id;
	public $f_create_folder;
	public $f_modify_folder;
	public $f_delete_folder;
	public $f_create_doc;
	public $f_modify_doc;
	public $f_delete_doc;
	public $f_create_shortcut;
	public $f_modify_shortcut;
	public $f_delete_shortcut;
	public $f_move;
	public $f_share;
	public $f_export;
	public $f_grant;
	public $f_scan;
	public $f_attach;
	public $f_print;
	public $f_annotate;
	public $f_assign_stamp;
	public $f_assign_uid;
	public $f_assign_role_id;
	public $f_assign_org_id;
	public $f_status;
	public $f_inherit;
}