<?php
/**
 * Entity Class for Table [tbl_sequence]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Sequence
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class SequenceEntity extends ADODB_Active_Record {
	public $_table = 'tbl_sequence';
	public $f_seq_name;
	public $f_seq_value;
	public $f_seq_step;
	public $f_seq_format;
	public $f_seq_type;
	public $f_seq_last_gen;
	public $f_seq_module;
	public $f_seq_run_type;
}