<?php
/**
 * Entity Class for Table [tbl_stat_usage]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บสถิติการใช้งาน
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class StatUsageEntity extends ADODB_Active_Record {
	public $_table = 'tbl_stat_usage';
	public $f_stat_id;
	public $f_acc_id;
	public $f_role_id;
	public $f_org_id;
	public $f_date;
	public $f_month;
	public $f_year;
	public $f_hour;
	public $f_minute;
	public $f_second;
	public $f_type;
	public $f_module;
	public $f_message;
}