<?php
/**
 * Entity Class for Table [tbl_sys_policy]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บPolicy ของระบบ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class SysPolicyEntity extends ADODB_Active_Record {
	public $_table = 'tbl_sys_policy';
	public $f_sys_policy_id;
	public $f_sys_policy_name;
	public $f_sys_policy_value;
	public $f_sys_policy_enable;
}