<?php
/**
 * Entity Class for Table [tbl_trans_df_recv]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Transaction การลงรับงานสารบรรณ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class TransDfRecvEntity extends ADODB_Active_Record {
	public $_table = 'tbl_trans_df_recv';
	public $f_recv_trans_main_id;
	public $f_recv_trans_main_seq;
	public $f_recv_id;
	public $f_recv_type;
	public $f_doc_recv_type;
	public $f_show_in_reg_book;
	public $f_reg_book_id;
	public $f_recv_reg_no;
	public $f_recv_reg_no_full;
	public $f_is_forwarded_trans;
	public $f_send_id;
	public $f_send_seq;
	public $f_send_trans_main_id;
	public $f_send_trans_main_seq;
	public $f_read;
	public $f_forwarded;
	public $f_accept_uid;
	public $f_accept_role_id;
	public $f_accept_org_id;
	public $f_recv_sys_stamp;
	public $f_recv_stamp;
	public $f_recv_date;
	public $f_recv_time;
	public $f_commit;
	public $f_commit_sys_stamp;
	public $f_commit_stamp;
	public $f_commit_date;
	public $f_commit_time;
	public $f_sendback;
	public $f_sendback_uid;
	public $f_sendback_role_id;
	public $f_sendback_org_id;
	public $f_cancel;
	public $f_cancel_uid;
	public $f_cancel_role_id;
	public $f_cancel_org_id;
	public $f_is_egif_trans;
	public $f_egif_recv_stamp;
	public $f_egif_reply_complete;
	public $f_send_fullname;
	public $f_send_org_name;
	public $f_attend_fullname;
	public $f_attend_org_name;
    public $f_recv_doc_type;
    public $f_receiver_uid;
    public $f_receiver_role_id;
    public $f_receiver_org_id;
    public $f_is_circ;
    public $f_governer_approve = 0;
    public $f_allow_circ = 0;
    public $f_recv_year;
    public $f_return_owner;
}