<?php
/**
 * Entity Class for Table [tbl_trans_master_df]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Transaction หลักงานสารบรรณ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class TransMasterDfEntity extends ADODB_Active_Record {
	public $_table = 'tbl_trans_master_df';
	public $f_trans_main_id;
	public $f_doc_id;
	public $f_start_type;
	public $f_start_stamp;
	public $f_start_date;
	public $f_start_time;
	public $f_stop_stamp;
	public $f_stop_date;
	public $f_stop_time;
	public $f_owner_type;
	public $f_owner_id;
	public $f_owner_role_id;
	public $f_owner_org_id;
	public $f_security_modifier;
	public $f_urgent_modifier;
	public $f_hold_job;
	public $f_hold_type;
	public $f_hold_uid;
	public $f_hold_role_id;
	public $f_hold_org_id;
	public $f_auto_route;
	public $f_route_seq;
	public $f_purpose;
	public $f_escalate_to;
	public $f_signed_by;
	public $f_expected_finish;
	public $f_trans_year;
	public $f_location;
	public $f_remark;
	public $f_expire_stamp;
	public $f_follow_up;
	public $f_deliver_method;
    public $f_abort=0;
}