<?php
/**
 * Entity Class for Table [tbl_trans_df_send]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Transaction การส่งงานสารบรรณ
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class TransDfSendEntity extends ADODB_Active_Record {
	public $_table = 'tbl_trans_df_send';
	public $f_send_trans_main_id;
	public $f_send_trans_main_seq;
	public $f_send_id;
	public $f_send_seq;
	public $f_send_type;
	public $f_show_in_reg_book;
	public $f_reg_book_id;
	public $f_send_reg_no;
	public $f_send_reg_no_full;
	public $f_is_forward_trans;
	public $f_recv_trans_main_id;
	public $f_recv_trans_main_seq;
	public $f_received;
	public $f_sendback;
	public $f_sendback_uid;
	public $f_sendback_role_id;
	public $f_sendback_org_id;
	public $f_sendback_comment;
	public $f_callback;
	public $f_callback_uid;
	public $f_callback_role_id;
	public $f_callback_org_id;
	public $f_callback_comment;
	public $f_request_action;
	public $f_sender_type;
	public $f_sender_uid;
	public $f_sender_role_id;
	public $f_sender_org_id;
	public $f_receiver_type;
	public $f_receiver_uid;
	public $f_receiver_role_id;
	public $f_receiver_org_id;
	public $f_send_sys_stamp;
	public $f_send_stamp;
	public $f_send_date;
	public $f_send_time;
	public $f_is_egif_trans;
	public $f_egif_send_stamp;
	public $f_egif_send_status;
	public $f_egif_recv_dept_id;
	public $f_egif_recv_ministry_id;
	public $f_egif_recv_reg_no;
	public $f_recv_fullname;
	public $f_recv_org_name;
	public $f_send_fullname;
	public $f_send_org_name;
    public $f_send_doc_type;
    public $f_sendback_ack;
    public $f_is_circ;
    public $f_governer_approve;
    public $f_callback_ack;    
    public $f_send_year;
    public $f_egif_recv_no;
	public $f_egit_recv_flag;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
}