<?php
/**
 * Entity Class for Table [tbl_workflow]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Workflow
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class WorkflowEntity extends ADODB_Active_Record {
	public $_table = 'tbl_workflow';
	public $f_wf_id;
	public $f_wf_revision;
	public $f_wf_name;
	public $f_wf_engine_version;
	public $f_wf_description;
	public $f_wf_deployed;
	public $f_wf_restricted;
	public $f_form_id;
	public $f_form_version;
	public $f_owner_type;
	public $f_owner_uid;
	public $f_owner_role_id;
	public $f_owner_org_id;
	public $f_use_default_controls;
	public $f_plugin;
	public $f_is_work_limit;
	public $f_work_limit_type;
	public $f_work_limit;
	public $f_supervisor_type;
	public $f_supervisor_uid;
	public $f_supervisor_role_id;
	public $f_supervisor_org_id;
	public $f_is_checkout;
	public $f_checkout_uid;
}