<?php
/**
 * Entity Class for Table [tbl_workflow_transition]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บ Workflow Transition
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class WorkflowTransitionEntity extends ADODB_Active_Record {
	public $_table = 'tbl_workflow_transition';
	public $f_wf_id;
	public $f_source_node;
	public $f_dest_node;
	public $f_transition_type;
	public $f_condition;
}