<?php
/**
 * Entity Class for Table [tbl_workflow_stats_node]
 * Extended from ADODB_Active_Record Class
 * Generated by SLC Entity Class Generator 1.0
 * Generate Date : 11/06/2008 , 23:38:34
 */
/**
 * Entity Class เก็บสถิติงาน Workflow ตาม Node
 * @author Mahasak Pijittum
 * @version 1.0.0
 * @package entity
 * @category entity
 *
 */
class WorkflowStatsNodeEntity extends ADODB_Active_Record {
	public $_table = 'tbl_workflow_stats_node';
	public $f_wf_instance_id;
	public $f_wf_id;
	public $f_wf_node_id;
	public $f_node_total_time;
}