<?php
global $config;
?>
<html>
	<head>
		<title>Benefit ECM : System Monitor</title>
		<script type="text/javascript" src="/<?php echo $config['appName'];?>/js/FusionCharts.js"></script>
		
	</head>
	<body>
		<center>
			<h3>Benefit ECM : System Monitor</h3>
			<table width="90%">
				<tr>
					<td width="50%">
						<fieldset>
							<legend>Concurrents</legend>
							<div id="concurrentDIV"></div>
						</fieldset>
					</td>
					<td  width="50%" align="left" valign="top">
						<fieldset>
							<legend>System Parameter</legend>
							<div>
								<ul>
									<li>Purchased Concurrent</li>
								</ul>
							</div>
						</fieldset>
					</td>
				</tr>
				
			</table>
		</center>		
		<script type="text/javascript">
	 	 	var myChart = new FusionCharts("/<?php echo $config['appName'];?>/swf/widget/RealTimeLine.swf", "concurrentChart", "450", "350", "0", "0");
	 	 	myChart.setDataURL("/<?php echo $config['appName'];?>/system-monitor/concurrent-data-config");
		 	myChart.render("concurrentDIV");
	    </script>
		
	</body>
</html>