<?php
global $config;
 ?>
<div id ="calendarWeekContainerDIV"></div>
<div id="calendarWeekDiv">
<table width="100%" border="1">
	<tr>	
		<td width="50"></td>
		<td>Sun</td>
		<td>Mon</td>
		<td>Tue</td>
		<td>Wed</td>
		<td>Thu</td>
		<td>Fri</td>
		<td>Sat</td>
	</tr>
	<?php for($hour = 0;$hour < 24 ;$hour++) { ?>
	<tr>
		<td><?php echo "{$hour}:00" ?></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<?php } ?>
</table>
</div>
<script type="text/javascript">
var calendarWeek = new Ext.Panel({
	//xtype:'portal',
	width: Ext.getCmp('tpAdmin').getInnerWidth()-5,
	height: Ext.getCmp('tpAdmin').getInnerHeight()-5,
	tbar: new Ext.Toolbar({
		id: 'calendarWeek_Toolbar',
		height: 25				
	}),
	border: false,
	frame: false,
	//height: '100%',
	id: 'panelCalendarWeek',
	autoScroll: true,
	contentEl: 'calendarWeekDiv',
	renderTo: 'calendarWeekContainerDIV',
	autoScroll:true,
	layout: 'column',
	iconCls: 'homeIcon',
	//items:[{$this->getPortletColumnLayout ( $config ['portlet'] ['style'] )}]
});
var tbCalendarMonth = Ext.getCmp('calendarWeek_Toolbar').add({
	text: '<<',
	disabled: false,
	handler: function() {
		Ext.get('calendarWeekContainerDIV').getUpdater().update({
			url: '/<?php echo $config ['appName'];  ?>/personal-calendar/week', 
			params: 'month=<?php echo $this->prevMonth; ?>&year=<?php echo $this->prevYear; ?>' ,
			scripts: true					
		});
		
	}
},new Ext.form.Label({
	text: '<?php
	echo $this->calendarMonth . " " . $this->calendarYear;
	?>',
	cls: 'calendarTextTBar'
}),{
	text: '>>',
	disabled: false,
	handler: function() {
		Ext.get('calendarWeekContainerDIV').getUpdater().update({
			url: '/<?php echo $config ['appName'];  ?>/personal-calendar/week', 
			params: 'month=<?php echo $this->nextMonth; ?>&year=<?php echo $this->nextYear; ?>' ,
			scripts: true					
		});
	}
},{
	text: '|',
	disabled: true
},{
	id: 'btnChangeWeekToDay',
	text:'Day',
	iconCls: 'calendarIcon',
	disabled: false,
	handler: function() {
		Ext.get('calendarWeekContainerDIV').getUpdater().update({
			url: '/<?php echo $config ['appName'];  ?>/personal-calendar/day', 
			scripts: true					
		});
	}
},{
	id: 'btnChangeWeekToMonth',
	text:'Month',
	iconCls: 'calendarIcon',
	disabled: false,
	handler: function() {
		Ext.get('calendarWeekContainerDIV').getUpdater().update({
			url: '/<?php echo $config ['appName'];  ?>/personal-calendar/month', 
			scripts: true					
		});
	}
},{
	id: 'btnChangeWeekToYear',
	text:'Year',
	iconCls: 'calendarIcon',
	disabled: false,
	handler: function() {
		Ext.get('calendarWeekContainerDIV').getUpdater().update({
			url: '/<?php echo $config ['appName'];  ?>/personal-calendar/year', 
			scripts: true					
		});
	}
});
calendarWeek.render();
</script>